[project]
name = "learn-nginx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Finsa-SC", email = "finsakusumaputra@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "gunicorn>=26.2.0",
    "uvicorn>=0.52.4",
]

