name: Auto Pull Server

on:
  push:
    branches:
      - main

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run test / check
        run: |
          uv sync
          uv run main.py